### ISSUE TITLE
rmq版本4.7.1，运行一段时间后会提示： FATAL | The service threw an unhandled exceptio

### ISSUE THREAD

**Issue by atzq1234** [NewLifeX/NewLife.RocketMQ#52]
2023-02-09 04:14:52,033 | FATAL | The service threw an unhandled exception | 44
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.SocketAsyncEventArgs'.
   at System.Net.Sockets.SocketAsyncEventArgs.ThrowForNonFreeStatus(Int32 status)
   at System.Net.Sockets.SocketAsyncEventArgs.SetBuffer(Byte[] buffer, Int32 offset, Int32 count)
   at NewLife.Net.SessionBase.ReleaseRecv(SocketAsyncEventArgs se, String reason)
   at NewLife.Net.SessionBase.ProcessEvent(SocketAsyncEventArgs se, Int32 bytes, Boolean ioThread)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by nnhy** [comment]
从错误本身来看，这是因为网络异常断开所致，只需要忽略即可

**Comment by atzq1234** [comment]
是的，是网络断开，但运行一段时间就会产生此问题，同一台服务器的其他服务没网络问题，只用到此组件的有问题。
我们在for循环中new producer(),会不会是这样使用导致线程数过多？

**Comment by nnhy** [comment]
对于生产者来说，建议使用固定数量的生产者 Producer，一般只用一个即可

**Comment by atzq1234** [comment]
是的，发现了两方面解决，一个是我们使用上的问题，已经固定生产者数量，几率降低很多；
然后感谢更新，看你们源码的更新，也在小概率异常catch内部的重试操作造成再次异常，在外层又加了一层trycatch来解决，更新到最新版X就能彻底解决；

**Comment by nnhy** [comment]
网络编程，最难的地方就在于容错处理。
大家为了省事，一般遇到错误就会重新建立一个连接，对于rmq这种长连接协议来说，每次新连接都要验证，比较繁琐

**Comment by atzq1234** [comment]
你们开源的这些底层组件，确实方便和帮助了很多上层做业务的开发人员。
