### ISSUE TITLE
消费端发布到服务器上报错

### ISSUE THREAD

**Issue by zt72065036** [NewLifeX/NewLife.RocketMQ#63]
Y T System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at NewLife.RocketMQ.ClusterClient.Invoke(RequestCode request, Object body, Object extFields, Boolean ignoreError)
   at NewLife.RocketMQ.BrokerClient.Ping()
   at NewLife.Threading.TimerScheduler.Execute(Object state)
请问这个错误是什么问题？谢谢，本地是不会有这个错误的，测试服务器才会报

**Comment by myokok** [comment]
感觉像是rocketmq连接失败造成的。

**Comment by zt72065036** [comment]
> 向Broker发送Ping心跳时，网络超时

我ping ip地址 -t 没有超时的，可以怎样解决呢？谢谢

**Comment by zt72065036** [comment]
重新捕获了源码里的异常，暂时解决，不知道有没有坑
