### ISSUE TITLE
用0401的版本，发布服务器上报错，如何解决

### ISSUE THREAD

**Issue by zt72065036** [NewLifeX/NewLife.RocketMQ#66]
17:11:43.263 53 Y T System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at NewLife.RocketMQ.ClusterClient.Invoke(RequestCode request, Object body, Object extFields, Boolean ignoreError)
   at NewLife.RocketMQ.BrokerClient.Ping()
   at NewLife.RocketMQ.BrokerClient.OnPing(Object state)
   at NewLife.Threading.TimerScheduler.Execute(Object state)
17:11:43.672 32 Y T System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at NewLife.RocketMQ.ClusterClient.SendAsync(Command cmd, Boolean waitResult)
   at NewLife.RocketMQ.ClusterClient.InvokeAsync(RequestCode request, Object body, Object extFields, Boolean ignoreError)
   at NewLife.RocketMQ.Consumer.UpdateOffset(MessageQueue mq, Int64 commitOffset)
   at NewLife.RocketMQ.Consumer.InitOffsetAsync()
   at NewLife.RocketMQ.Consumer.Rebalance()
   at NewLife.RocketMQ.Consumer.CheckGroup(Object state)

用0401版本，发布测试会报以上错误，请问如何处理，谢谢，网络是正常的

**Comment by nnhy** [comment]
这是因为无法连接broker服务器

**Comment by nnhy** [comment]
应用程序不仅要能够连通NameServer，还要能够连通Broker所在的所有服务器节点
