### ISSUE TITLE
.net core 程序连接华为云rocketmq启动失败

### ISSUE THREAD

**Issue by HYT810** [NewLifeX/NewLife.RocketMQ#74]
![image](https://github.com/NewLifeX/NewLife.RocketMQ/assets/37981766/cefba362-f4e6-4c26-9e9c-1fc16ccc6c93)

**Comment by HYT810** [comment]
#详解：https://newlifex.com/core/log
#字段: 时间 线程ID 线程池Y/网页W/普通N/定时T 线程名/任务ID 消息内容
#Fields: Time ThreadID Kind Name Message
16:55:23.683  1 N - NewLife.Core v10.6.2024.0101 Build 2024-01-01 .NET 6.0
16:55:23.686  1 N - NewLife组件核心库 ©2002-2023 NewLife
16:55:23.689  1 N - RocketMQDemo v1.0.0 Build 2000-01-01 .NET 6.0
16:55:23.689  1 N - RocketMQDemo 
16:55:23.689  1 N - NewLife.RocketMQ v2.5.2024.0101 Build 2024-01-01 05:22:28 .NET Standard 2.1
16:55:23.689  1 N - RocketMQ客户端 ©2002-2024 新生命开发团队
16:55:25.230  1 N - [DEFAULT_PRODUCER]正在从名称服务器[10.37.134.46:8100]查找该Topic所在Broker服务器地址列表
16:55:25.238  1 N - [topic_task_model_deal]集群地址：tcp://10.37.134.46:8100
16:55:25.239  1 N - [topic_task_model_deal]正在连接[tcp://10.37.134.46:8100]
16:55:25.257  1 N - Tcp.Open tcp://0.0.0.0:2979=>10.37.134.46:8100
16:55:25.406  7 Y - Tcp.Close EmptyData tcp://0.0.0.0:2979=>10.37.134.46:8100
16:55:25.457  1 N - System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at NewLife.RocketMQ.ClusterClient.Invoke(RequestCode request, Object body, Object extFields, Boolean ignoreError)
   at NewLife.RocketMQ.NameClient.GetRouteInfo(String topic)
   at NewLife.RocketMQ.Client.MqBase.Start()
   at NewLife.RocketMQ.Producer.Start()
   at RocketMQDemo.Program.Main(String[] args) in D:\Study\RocketMQDemo\RocketMQDemo\Program.cs:line 18

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at NewLife.RocketMQ.ClusterClient.Invoke(RequestCode request, Object body, Object extFields, Boolean ignoreError)
   at NewLife.RocketMQ.NameClient.GetRouteInfo(String topic)
   at NewLife.RocketMQ.Client.MqBase.Start()
   at NewLife.RocketMQ.Producer.Start()
   at RocketMQDemo.Program.Main(String[] args) in D:\Study\RocketMQDemo\RocketMQDemo\Program.cs:line 18
16:55:25.462  1 N - 异常退出！

**Comment by nnhy** [comment]
看样子是网络刚连上就断开了，试一下telnet是否正常。
再试一下 newlife.rocketmq / newlife.core 更换不同版本

**Comment by nnhy** [comment]
经测试支持 Apache RocketMQ v5.3 ！

v2.6.2024.1004 支持RocketMQ v5.3，在公网测试通过。默认内网broker地址替换为公网地址。https://github.com/NewLifeX/NewLife.RocketMQ/commit/006817ea918d48c83b2fb0f1318a8a3b339f9528
